package com.example.android.popularmovies.domain;

import android.os.Parcel;
import android.os.Parcelable;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Created by calin on 09/02/2017.
 *
 * Parcelable code generated by http://www.parcelabler.com/
 */

public class Movie implements Parcelable {

	private String posterPath;
	private Boolean adult;
	private String overview;
	private Date releaseDate;
	private List<Integer> genreIds;
	private Integer id;
	private String originalTitle;
	private String originalLanguage;
	private String title;
	private String backdropPath;
	private Double popularity;
	private Integer voteCount;
	private Boolean video;
	private Double voteAverage;



	protected Movie(Parcel in) {
		posterPath = in.readString();
		byte adultVal = in.readByte();
		adult = adultVal == 0x02 ? null : adultVal != 0x00;
		overview = in.readString();
		long tmpReleaseDate = in.readLong();
		releaseDate = tmpReleaseDate != -1 ? new Date(tmpReleaseDate) : null;
		if (in.readByte() == 0x01) {
			genreIds = new ArrayList<>();
			in.readList(genreIds, Integer.class.getClassLoader());
		} else {
			genreIds = null;
		}
		id = in.readByte() == 0x00 ? null : in.readInt();
		originalTitle = in.readString();
		originalLanguage = in.readString();
		title = in.readString();
		backdropPath = in.readString();
		popularity = in.readByte() == 0x00 ? null : in.readDouble();
		voteCount = in.readByte() == 0x00 ? null : in.readInt();
		byte videoVal = in.readByte();
		video = videoVal == 0x02 ? null : videoVal != 0x00;
		voteAverage = in.readByte() == 0x00 ? null : in.readDouble();
	}

	@Override
	public int describeContents() {
		return 0;
	}

	@Override
	public void writeToParcel(Parcel dest, int flags) {
		dest.writeString(posterPath);
		if (adult == null) {
			dest.writeByte((byte) (0x02));
		} else {
			dest.writeByte((byte) (adult ? 0x01 : 0x00));
		}
		dest.writeString(overview);
		dest.writeLong(releaseDate != null ? releaseDate.getTime() : -1L);
		if (genreIds == null) {
			dest.writeByte((byte) (0x00));
		} else {
			dest.writeByte((byte) (0x01));
			dest.writeList(genreIds);
		}
		if (id == null) {
			dest.writeByte((byte) (0x00));
		} else {
			dest.writeByte((byte) (0x01));
			dest.writeInt(id);
		}
		dest.writeString(originalTitle);
		dest.writeString(originalLanguage);
		dest.writeString(title);
		dest.writeString(backdropPath);
		if (popularity == null) {
			dest.writeByte((byte) (0x00));
		} else {
			dest.writeByte((byte) (0x01));
			dest.writeDouble(popularity);
		}
		if (voteCount == null) {
			dest.writeByte((byte) (0x00));
		} else {
			dest.writeByte((byte) (0x01));
			dest.writeInt(voteCount);
		}
		if (video == null) {
			dest.writeByte((byte) (0x02));
		} else {
			dest.writeByte((byte) (video ? 0x01 : 0x00));
		}
		if (voteAverage == null) {
			dest.writeByte((byte) (0x00));
		} else {
			dest.writeByte((byte) (0x01));
			dest.writeDouble(voteAverage);
		}
	}

	@SuppressWarnings("unused")
	public static final Parcelable.Creator<Movie> CREATOR = new Parcelable.Creator<Movie>() {
		@Override
		public Movie createFromParcel(Parcel in) {
			return new Movie(in);
		}

		@Override
		public Movie[] newArray(int size) {
			return new Movie[size];
		}
	};

	public String getPosterPath() {
		return posterPath;
	}

	public void setPosterPath(String posterPath) {
		this.posterPath = posterPath;
	}

	public Boolean getAdult() {
		return adult;
	}

	public void setAdult(Boolean adult) {
		this.adult = adult;
	}

	public String getOverview() {
		return overview;
	}

	public void setOverview(String overview) {
		this.overview = overview;
	}

	public Date getReleaseDate() {
		return releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	public List<Integer> getGenreIds() {
		return genreIds;
	}

	public void setGenreIds(List<Integer> genreIds) {
		this.genreIds = genreIds;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getOriginalTitle() {
		return originalTitle;
	}

	public void setOriginalTitle(String originalTitle) {
		this.originalTitle = originalTitle;
	}

	public String getOriginalLanguage() {
		return originalLanguage;
	}

	public void setOriginalLanguage(String originalLanguage) {
		this.originalLanguage = originalLanguage;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getBackdropPath() {
		return backdropPath;
	}

	public void setBackdropPath(String backdropPath) {
		this.backdropPath = backdropPath;
	}

	public Double getPopularity() {
		return popularity;
	}

	public void setPopularity(Double popularity) {
		this.popularity = popularity;
	}

	public Integer getVoteCount() {
		return voteCount;
	}

	public void setVoteCount(Integer voteCount) {
		this.voteCount = voteCount;
	}

	public Boolean getVideo() {
		return video;
	}

	public void setVideo(Boolean video) {
		this.video = video;
	}

	public Double getVoteAverage() {
		return voteAverage;
	}

	public void setVoteAverage(Double voteAverage) {
		this.voteAverage = voteAverage;
	}
}
